@token = aa1f315d5e2ad8de716d

POST http://localhost:8080/reservation
Authorization: {{token}}
Content-Type: application/json

{
    "user": "user1",
    "startDate": "startDate",
    "endDate":"endDate",
    "room": "someRoom"
}
###

GET http://localhost:8080/reservation/78cb759e098221e376dc
Authorization: {{token}}
###

GET http://localhost:8080/reservation/all
Authorization: {{token}}
###

PUT http://localhost:8080/reservation/78cb759e098221e376dc
Authorization: {{token}}
Content-Type: application/json

{
    "room": "someOtherRoom",
    "user": "user2"

}
###